name: School Task
description: Track a school deliverable
labels: ["type:schedule"]
body:
  - type: input
    id: course
    attributes: { label: Course, placeholder: "MAP2302" }
    validations: { required: true }
  - type: input
    id: assignment
    attributes: { label: Assignment, placeholder: "HW1 - Laplace" }
    validations: { required: true }
  - type: input
    id: due
    attributes: { label: Due (ISO 8601) }
  - type: textarea
    id: scope
    attributes: { label: Scope, placeholder: "Problems 1–8; show all Laplace steps." }
