[project]
name = "jonnyjr-py"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["requests>=2.32.3", "pytest>=8.3.3", "coverage>=7.6.1", "pytest-cov>=5.0.0"]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = ["E", "F", "I"]

[tool.pytest.ini_options]
addopts = "-q --cov=packages/py/src --cov-report=xml:coverage.xml --cov-report=html:coverage_html"
