name: Docs CI
on:
  push:
    paths: ["**/*.md", ".markdownlint.json"]
  pull_request:
    paths: ["**/*.md", ".markdownlint.json"]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Lint markdown files
        run: markdownlint '**/*.md' --ignore node_modules --ignore dist
